spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: ORACLE
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: wholesale
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true

application:
  postgre:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: admin
      maxPoolSize: 2